import Header from "@/components/Header";
import Footer from "@/components/Footer";



export const metadata = {
  title: "testing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <section>
        <Header />
       {children}
       <Footer />
   </section>
        
       
        
        
     
  );
}
