import Header from "@/components/Header";



export const metadata = {
  title: "testing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <section>
        <Header />
       {children}
       <h1>Footer</h1>
   </section>
        
       
        
        
     
  );
}
