
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
      <section className="min-h-full flex flex-col">
        
        <h1>authtication</h1>
        {children}
        
        
        </section>

  );
}
